# ============================================
# CONFIGURACIÓN MYSQL - Librería La Esperanza
# ============================================
# Si falla el login a la BD, cambia SOLO db.password
# por la contraseña que usas en MySQL Workbench.

db.url=jdbc:mysql://localhost:3306/libreria_esperanza?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
db.user=root
db.password=root
