# Copia este archivo como db.properties y coloca tus datos locales.
# NO subas db.properties con contraseñas reales a GitHub.
db.url=jdbc:mysql://localhost:3306/libreriadb_in4cm?serverTimezone=UTC
db.user=root
db.password=#Ndim4AM
